spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.31.245:3306/gulimall_ums
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.245:8848
  application:
    name: gulimall-member
mybatis-plus:
  mapper-location: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 8000