spring:
  application:
    name: gulimall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.245:8848
    gateway:
      routes:
        - id: test
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}

# 前端项目已/api开头访问
# RewritePath 将localhsot/api/** 转成 localhost/renren-fast/**
server:
  port: 88
